<div class="header_02"><?=$this->translate->_('farmaceutica');?></div>
            
<p class="em_text"><?=$this->translate->_('Talvez a área mais exigente para a produção de embalagens, a área farmacêutica exige uma garantia de elevados padrões de consistência e desempenho. ');?></p>

<p class="em_text"><?=$this->translate->_('A Fernandes e Terceiro, S.A. é o fornecedor preferencial de um determinado número de laboratórios. Acreditação ISO 9001 e rigoroso controle de qualidade de produção garantem embalagens de alta qualidade, capazes de suportar os rigores de ambientes estéreis médicos e laboratoriais.');?></p>

<div id='coin-slider'>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph1.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph2.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph3.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph4.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph5.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph6.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/pharma/ph7.jpg' alt="Foto" />
	</a>
</div>


            
<div class="margin_bottom_20"></div>
            

<div class="cleaner"></div>

</div>