<div class="header_02"><?=$this->translate->_('custom');?></div>
            
<p class="em_text"><?=$this->translate->_('Desde do conceito, protótipo, a produção, podemos oferecer um serviço completo de design feitos por encomenda com um objetivo claro em mente: tornar os seus produtos únicos e apelativos.');?></p>
<p class="em_text"><?=$this->translate->_('Produzimos uma grande variedade de estilos de embalagens. Trabalhos com o cliente para determinar a configuração ideal de embalagens especialmente para o seu produto e orçamento.');?></p>
<p class="em_text"><?=$this->translate->_('Para novos projetos, produzimos amostras protótipo em poucos dias para que os clientes possam avaliar o projeto antes de avançar para a fase de produção. Qualquer modificação no projeto pode ser facilmente realizado nesta fase que antecede a de produção.');?></p>

<div id='coin-slider'>
	<a href="#">
		<img src='/plugins/images/coin-slider/custom/custom1.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/custom/custom2.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/custom/custom3.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/custom/custom4.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/custom/custom5.jpg' alt="Foto" />
	</a>
	
</div>


            
<div class="margin_bottom_20"></div>
            

<div class="cleaner"></div>

</div>