<div class="header_02"><?=$this->translate->_('expositores');?></div>
            
<p class="em_text"><?=$this->translate->_('Quando se tenta vender um produto, tem que mantê-lo aos olhos do público.');?></p>
<p class="em_text"><?=$this->translate->_('Por isso precisa de expositores práticos que mantêm o seu produto onde os clientes o possam ver.');?></p>
<p class="em_text"><?=$this->translate->_('Desde pequenos pendurantes a expositores de gamas inteiras, a Fernandes e Terceiro, S.A., dispõe da solução para o sucesso da sua marca.');?></p>


<div id='coin-slider'>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo1.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo2.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo3.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo4.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo5.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo6.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/expo/expo7.jpg' alt="Foto" />
	</a>
	
</div>

<div class="margin_bottom_20"></div>
            
<div class="cleaner"></div>

</div>