<div class="header_02"><?=$this->translate->_('promocionais');?></div>
            
<p class="em_text"><?=$this->translate->_('Podem ser de várias formas para auxiliar a promoção do produto e as vendas, criando um ponto de diferença.');?></p>
<p class="em_text"><?=$this->translate->_('Caixas promocionais são uma ferramenta de marketing muito eficaz, influenciando o comportamento de compra do cliente. As nossas caixas são atraentes e capazes de captar a atenção do consumidor.');?></p>
<p class="em_text"><?=$this->translate->_('Existem muitas variedades, formas e tamanhos disponíveis.');?></p>


<div id='coin-slider'>
	<a href="#">
		<img src='/plugins/images/coin-slider/promo/promo1.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/promo/promo2.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/promo/promo3.jpg' alt="Foto" />
	</a>
	<a href="#">
		<img src='/plugins/images/coin-slider/promo/promo4.jpg' alt="Foto" />
	</a>
</div>


            
<div class="margin_bottom_20"></div>
            

<div class="cleaner"></div>

</div>