<div class="header_02"><?=$this->translate->_('bib');?></div>
            
<p class="em_text"><?=$this->translate->_('Bag-in-box (BIB) é uma forma flexível, formato de embalagem ecológica para os líquidos. EFornece uma alternativa competitiva para embalagens, como garrafas de vidro e plástico.');?></p>
<p class="em_text"><?=$this->translate->_('Existem benefícios práticos como econômicos em relação à embalagem padrão, tais como:');?></p>
<ul>
<li><?=$this->translate->_('Prazo de conservação após a abertura - até 8 semanas;');?></li>
<li><?=$this->translate->_('Excelente proteção de barreira contra luz e oxigênio;');?></li>
<li><?=$this->translate->_('Menor utilização de materiais e reciclagem;');?></li>
<li><?=$this->translate->_('User-friendly e inviolável;');?></li>
<li><?=$this->translate->_('Embalagens de diferentes tamanhos podem ser enchidas na mesma máquina;');?></li>
<li><?=$this->translate->_('Uma fração do peso de outras embalagens.');?></li>
</ul>


<div id='coin-slider'>
	<a href="#">
		<img src='/plugins/images/coin-slider/bib/bib1.jpg' alt="Foto" />
	</a>
	
</div>


            
<div class="margin_bottom_20"></div>
            

<div class="cleaner"></div>

</div>






