<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?= $this->translate->_('titulo'); ?></title>
<?= $this->headMeta();?>
<?= $this->headLink(); ?>
<?= $this->headScript();?>
<script type="text/javascript" src="/js/jquery.cycle.js"></script>
<!--[if lt IE 7]>
  <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='AVISO!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>Você está usando um navegador desatualizado</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>Para navegar melhor neste site, por favor, actualize seu navegador.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://pt-pt.www.mozilla.com/pt-PT/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.microsoft.com/downloads/details.aspx?FamilyID=341c2ad5-8c3d-4347-8c03-08cdecd8852b&DisplayLang=pt-pt' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/pt/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome?hl=pt-PT' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
  </div>
<![endif]-->
<script type="text/javascript">
$(document).ready(function() {$('.slideshow').cycle({fx: 'fade'});});
</script>
</head>
<body>
<div id="templatemo_header_wrapper">
<!--  Free Web Templates by TemplateMo.com  -->
  <div id="templatemo_header">
    <div id="site_logo"><a href="/"><img src="/images/logof3.jpg" alt ="F3 Logo" /></a></div>
        <div id="templatemo_menu">
      		<div id="templatemo_menu_left"></div>
      		<?php 
      		$session = new Zend_Session_Namespace('rps.l10n');
            switch ($session->locale) {
                case 'es_ES':
                   echo $this->ES();
                break;
                
                default:
                    echo $this->PT();
                break;
            } ?>
            	
		</div> <!-- end of menu -->
    </div>  <!-- end of header -->
</div> <!-- end of header wrapper -->

<div id="templatemo_banner_wrapper">
	<div id="templatemo_banner">
    	<div id="templatemo_banner_image">
        	<div id="templatemo_banner_image_wrapper">
            	<div class="slideshow">
            		<img src="/images/bib1_3D.jpg" alt="image" />
					<img src="/images/bib1_3D1.jpg" alt="image" />
					<img src="/images/bib1_3D2.jpg" alt="image" />
					<img src="/images/bib1_3D3.jpg" alt="image" />	
            	</div>
            </div>
        </div>
        
        <div id="templatemo_banner_content">
        	<div class="header_01"><?=$this->translate->_('Trabalhe com um líder na indústria de Cartonagem');?></div>
            <p><?=$this->translate->_('Fornecemos soluções inovadoras e resultados sustentáveis para os nossos clientes.');?> </p>
        </div>	
    <div class="cleaner"></div>
    </div> <!-- end of banner -->
</div> <!-- end of banner wrapper -->

<div id="templatemo_content_wrapper">
	<div id="templatemo_content">
    
    	<div id="column_w530">
    	
    	<?=$this->layout()->content; ?>
        	
            <div class="header_02"><?=$this->translate->_('Design e Inovação');?></div>
            
            <p class="em_text"><?=$this->translate->_('O objectivo de uma embalagem é criar impacto, e é por isso que a Fernandes e Terceiro reconhece que a inovação na forma de um projecto é a chave para o sucesso da sua marca.');?></p>
            <p class="em_text"><?=$this->translate->_('Os nossos clientes têm acesso às plataformas de última tecnologia, capacidades de fabricação diverso, e desenhos criativos.');?></p>
            <p class="em_text"><?=$this->translate->_('Os nossos mais recentes recursos tecnológicos, oferecem soluções únicas aos nossos clientes, incluindo:');?></p>
            
            <div class="margin_bottom_20"></div>
            
            <div class="margin_bottom_20"></div>           
            
            <div class="content_section_02">
            	<?=$this->translate->_('O trabalho da equipa de design trabalha em estreita colaboração com as equipas de marketing, técnica e de produção para trazer idéias inovadoras de embalagem e convertê-los em realidade comercial. As características funcionais e estéticas combinam-se para formar uma solução de embalagem única para nossos clientes.');?>
            </div>
            
            <div class="cleaner"></div>
        </div>
            <?=$this->RightBox();?>
       	<div class="cleaner"></div>
        </div>
    
    	<div class="cleaner"></div>
     <!-- end of content wrapper -->
</div> <!-- end of content wrapper -->

<?=$this->Footer();?>
</body>
</html>