<?php
if ($this->current == "es") {
    $current = '<ul><li><a href="/">&nbsp;&nbsp;Português</a></li><li><a href="/es/" class="current">Español</a></li><li><a href="contacts" class="last">Contactos</a></li></ul> ';
} else {
    $current = '<ul><li><a href="/" class="current">&nbsp;&nbsp;Português</a></li><li><a href="/es/">Español</a></li><li><a href="contacts" class="last">Contactos</a></li></ul> ';
}
$this->translate()->getLocale();
$this->placeholder('menu')->set('<div id="templatemo_menu">
      		<div id="templatemo_menu_left"></div>
               	' . $current . '
		</div> <!-- end of menu -->');
$this->placeholder('banner')->set('<div id="templatemo_banner_wrapper">
	<div id="templatemo_banner">
	    <div id="templatemo_banner_image">
        	<div id="templatemo_banner_image_wrapper">
				<div class="slideshow">
            		<img src="/images/bib1_3D.jpg" alt="image" />
					<img src="/images/bib1_3D1.jpg" alt="image" />
					<img src="/images/bib1_3D2.jpg" alt="image" />
				</div>	
            </div>
        </div>
        <div id="templatemo_banner_content">
        	<div class="header_01">' . $this->translate('vindo') . '</div>
            <p>Aliquam dignissim elementum est sit amet iaculis. Integer pretium ultricies risus, condimentum molestie odio euismod vitae. </p>
            <div class="button_01"><a href="#">Read more</a></div>
        </div>	
    	<div class="cleaner"></div>
    </div> <!-- end of banner -->
</div> <!-- end of banner wrapper -->');
?>
<h2><a href="<?=$this->BaseUrl() . $this->translate('link');?>">Link</a></h2>

<div class="header_02">Welcome to our WEBSITE!</div>

<p class="em_text">This is a professional XHTML/CSS layout provided by <a
	href="http://www.templatemo.com" target="_parent">TemplateMo.com</a>
for free of charge. You can use this template for any purpose. Credit
goes to <a href="http://www.photovaco.com" target="_blank">Free Photos</a>
for photos.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a
justo dolor. Duis in tincidunt lorem. Nunc et tellus nisi. Nulla non
velit lectus. Morbi luctus ullamcorper felis, non gravida neque congue
sit amet.</p>

<div class="margin_bottom_20"></div>

<ul class="content_list_01">
	<li>Integer tempor, libero quis laoreet dapibus, quam mauris hendrerit
	urna, vel feugiat dolor lectus non velit. Fusce at nisl libero, ac
	fringilla risus.</li>
	<li>Proin non velit nec enim volutpat euismod. Phasellus lorem velit,
	porttitor non iaculis in, euismod a metus. Nullam orci odio, dignissim
	a egestas ac, sollicitudin in quam.</li>
</ul>

<div class="margin_bottom_20"></div>

<div class="content_section_01">Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Aliquam a justo dolor. Duis in tincidunt lorem. Nunc et
tellus nisi. Nulla non velit lectus. Morbi luctus ullamcorper felis, non
gravida neque congue sit amet. Nam nec mi metus, ac elementum velit.
Etiam vel arcu velit, eget consequat risus.</div>

<div class="cleaner"></div>